version: '3.7'
services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:20.04
    environment:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    entrypoint: /bin/bash