version: '3.1'

services:
    localstack:
        container_name: localstack-ui
        image: localstack/localstack-full:latest
        ports:
            - "4566-4599:4566-4599"
            - "${PORT_WEB_UI-8090}:${PORT_WEB_UI-8090}"
        environment:
            - SERVICES=s3,dynamodb,cloudformation,sts
            - DEBUG=1
            - LOCALSTACK_HOSTNAME=localstack
            - DATA_DIR=${DATA_DIR- }
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DEFAULT_REGION=us-west-2
            - HOSTNAME_EXTERNAL=localstack
            - START_WEB=1
            # - DATA_DIR=/tmp/localstack
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - test
networks:
    test: